
function Do () {

	try {
	    something.run()
	    let a = 2 + 3
	    // throw "Tantrum"
	} catch (err) {
		console.log('Ooopps... ', err)
	}
  
}

Do()
